
version: '3.7'

services:

  starter_client:
    build:
      context: test_client
    user: nobody
    image: cyberdojo/test-starter-client
    init: true
    container_name: test-starter-client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - custom
      - exercises
      - languages
    restart: 'no'
    ports: [ "4528:4528" ]

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  custom:
    user: nobody
    image: cyberdojo/test-custom
    init: true
    container_name: test-custom-server
    environment: [ NO_PROMETHEUS ]
    volumes: [ "./test_custom_server:/app/test:ro" ]
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    ports: [ "4526:4526" ]

  exercises:
    user: nobody
    image: cyberdojo/test-exercises
    init: true
    container_name: test-exercises-server
    environment: [ NO_PROMETHEUS ]
    volumes: [ "./test_exercises_server:/app/test:ro" ]
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    ports: [ "4525:4525" ]

  languages:
    user: nobody
    image: cyberdojo/test-languages
    init: true
    container_name: test-languages-server
    environment: [ NO_PROMETHEUS ]
    volumes: [ "./test_languages_server:/app/test:ro" ]
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    ports: [ "4524:4524" ]
