
version: '3.7'

services:

  starter_client:
    build:
      context: test_client
    user: nobody
    image: cyberdojo/test-starter-client
    init: true
    container_name: test-starter-client
    read_only: true
    depends_on:
      - custom
      - exercises
      - languages
    restart: 'no'
    ports: [ "4528:4528" ]
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 52428800 # 50MB

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  custom:
    user: nobody
    image: cyberdojo/test-custom
    build:
      context: app
    container_name: test-custom-server
    read_only: true
    restart: 'no'
    ports: [ "${CYBER_DOJO_CUSTOM_START_POINTS_PORT}:${CYBER_DOJO_CUSTOM_START_POINTS_PORT}" ]
    volumes:
      - "./test_custom_server:/app/test:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 52428800 # 50MB

  exercises:
    user: nobody
    image: cyberdojo/test-exercises
    build:
      context: app
    container_name: test-exercises-server
    read_only: true
    restart: 'no'
    ports: [ "${CYBER_DOJO_EXERCISES_START_POINTS_PORT}:${CYBER_DOJO_EXERCISES_START_POINTS_PORT}" ]
    volumes:
      - "./test_exercises_server:/app/test:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 52428800 # 50MB

  languages:
    user: nobody
    image: cyberdojo/test-languages
    build:
      context: app
    container_name: test-languages-server
    read_only: true
    restart: 'no'
    ports: [ "${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}:${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}" ]
    volumes:
      - "./test_languages_server:/app/test:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 52428800 # 50MB
