version: 2
jobs:
  build-tag-publish:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Build image, test it, tag it, publish it
          command: ./build_test_publish.sh

workflows:
  version: 2
  build-tag-publish:
    jobs:
      - build-tag-publish:
          context: cyberdojo-context
          filters:
            branches:
              only: [ master ]
