version: 2
jobs:
  build-publish-trigger:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Curl cyber-dojo script
          command: |
            set -e
            curl \
              --silent \
              --fail \
              https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo \
              --output /tmp/cyber-dojo
            chmod 700 /tmp/cyber-dojo
      - run:
          name: Build image, test it, tag it, publish it
          command: ./build_test_tag_publish.sh

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only: [ master ]
