version: 2
jobs:
  build-publish-trigger:

    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Curl cyber-dojo script
          command: |
            set -e
            curl \
              --silent \
              --fail \
              https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo \
              --output /tmp/cyber-dojo
            chmod 700 /tmp/cyber-dojo
      - run:
          name: Build (untested) docker image
          command: |
            set -e
            #./pipe_build_up_test.sh
            ./sh/build_base_docker_image.sh
      - run:
          name: Tag docker image
          command: |
            set -e
            declare -r NAME="${CIRCLE_PROJECT_REPONAME}"
            declare -r TAG="${CIRCLE_SHA1:0:7}"
            docker tag cyberdojo/${NAME}:latest cyberdojo/${NAME}:${TAG}
      - run:
          name: Publish tagged docker image on dockerhub
          command: |
            set -e
            declare -r NAME="${CIRCLE_PROJECT_REPONAME}"
            declare -r TAG="${CIRCLE_SHA1:0:7}"
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push cyberdojo/${NAME}:${TAG}
            docker push cyberdojo/${NAME}:latest
            docker logout
      - run:
          name: Trigger dependent repos
          command: |
            set -e
            TRIGGER=trigger-dependent-repos.sh
            curl -O --fail ${CIRCLECI_SCRIPT_DIR}/${TRIGGER}
            chmod 700 ./${TRIGGER}
            # ./${TRIGGER} custom exercises languages # Off till fixed

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
